<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Http;
use App\Models\SteeringCollection;
use App\Models\SteeringDoc;

class CrawlGitHubSteeringDocs extends Command
{
    protected $signature = 'crawl:steering-docs {--limit=100}';
    protected $description = 'Crawl GitHub for projects with AI steering docs';

    private array $folders = ['.claude', '.cursor', '.ai', '.kiro', '.aider', '.windsurf'];
    private array $crawled = [];

    public function handle()
    {
        $this->info('🚀 Starting GitHub steering docs crawler...');
        
        $repos = $this->getTopRepos();
        
        $this->info("Queueing {$repos->count()} repos...");
        
        foreach ($repos as $repo) {
            \App\Jobs\CrawlRepoSteeringDocs::dispatch($repo);
        }
        
        $this->info("✅ Queued all repos. Check Horizon for progress.");
    }

    private function getTopRepos()
    {
        // Top 500 GitHub repos by stars (as of Feb 2026)
        return collect([
            // Top 50 (100k+ stars)
            'freeCodeCamp/freeCodeCamp',
            'EbookFoundation/free-programming-books',
            'sindresorhus/awesome',
            'public-apis/public-apis',
            'jwasham/coding-interview-university',
            'kamranahmedse/developer-roadmap',
            '996icu/996.ICU',
            'vuejs/vue',
            'facebook/react',
            'tensorflow/tensorflow',
            'twbs/bootstrap',
            'ohmyzsh/ohmyzsh',
            'flutter/flutter',
            'microsoft/vscode',
            'torvalds/linux',
            'gitignore/gitignore',
            'nodejs/node',
            'angular/angular',
            'rust-lang/rust',
            'denoland/deno',
            
            // JavaScript/TypeScript (50-150)
            'vercel/next.js',
            'facebook/react-native',
            'microsoft/TypeScript',
            'axios/axios',
            'nodejs/node',
            'mrdoob/three.js',
            'goldbergyoni/nodebestpractices',
            'ryanmcdermott/clean-code-javascript',
            'trekhleb/javascript-algorithms',
            'airbnb/javascript',
            'leonardomso/33-js-concepts',
            'typescript-cheatsheets/react',
            'sudheerj/reactjs-interview-questions',
            'yangshun/tech-interview-handbook',
            'h5bp/html5-boilerplate',
            'jquery/jquery',
            'lodash/lodash',
            'moment/moment',
            'expressjs/express',
            'meteor/meteor',
            'socketio/socket.io',
            'webpack/webpack',
            'parcel-bundler/parcel',
            'vitejs/vite',
            'rollup/rollup',
            'esbuild/esbuild',
            'babel/babel',
            'prettier/prettier',
            'eslint/eslint',
            'standard/standard',
            
            // Frameworks (150-200)
            'sveltejs/svelte',
            'remix-run/remix',
            'nuxt/nuxt',
            'gatsbyjs/gatsby',
            'nestjs/nest',
            'strapi/strapi',
            'electron/electron',
            'tauri-apps/tauri',
            'ionic-team/ionic-framework',
            'quasarframework/quasar',
            'vuejs/core',
            'preactjs/preact',
            'solidjs/solid',
            'qwikdev/qwik',
            'astro-build/astro',
            'redwoodjs/redwood',
            'blitz-js/blitz',
            
            // CSS/Design (200-230)
            'tailwindlabs/tailwindcss',
            'animate-css/animate.css',
            'necolas/normalize.css',
            'daneden/animate.css',
            'IanLunn/Hover',
            'jgthms/bulma',
            'primer/css',
            'pure-css/pure',
            'foundation/foundation-sites',
            'semantic-org/semantic-ui',
            'ant-design/ant-design',
            'mui/material-ui',
            'chakra-ui/chakra-ui',
            'styled-components/styled-components',
            'emotion-js/emotion',
            'sass/sass',
            'less/less.js',
            'postcss/postcss',
            
            // PHP/Laravel (230-280)
            'laravel/laravel',
            'laravel/framework',
            'symfony/symfony',
            'composer/composer',
            'guzzle/guzzle',
            'PHPMailer/PHPMailer',
            'sebastianbergmann/phpunit',
            'doctrine/orm',
            'phpstan/phpstan',
            'filamentphp/filament',
            'livewire/livewire',
            'spatie/laravel-permission',
            'barryvdh/laravel-debugbar',
            'laravel/jetstream',
            'laravel/breeze',
            'laravel/horizon',
            'laravel/telescope',
            'laravel/sanctum',
            'laravel/fortify',
            'laravel/octane',
            'laravel/vapor-core',
            'spatie/laravel-medialibrary',
            'spatie/laravel-backup',
            'spatie/laravel-activitylog',
            'spatie/laravel-query-builder',
            'spatie/laravel-data',
            'nunomaduro/collision',
            'pestphp/pest',
            'mockery/mockery',
            'vlucas/phpdotenv',
            'ramsey/uuid',
            'nesbot/carbon',
            'monolog/monolog',
            'league/flysystem',
            'intervention/image',
            'predis/predis',
            'phpredis/phpredis',
            
            // Python (280-330)
            'python/cpython',
            'tensorflow/models',
            'keras-team/keras',
            'scikit-learn/scikit-learn',
            'pandas-dev/pandas',
            'numpy/numpy',
            'matplotlib/matplotlib',
            'django/django',
            'flask/flask',
            'fastapi/fastapi',
            'pallets/click',
            'requests/requests',
            'psf/requests',
            'httpie/httpie',
            'scrapy/scrapy',
            'celery/celery',
            'pytest-dev/pytest',
            'sphinx-doc/sphinx',
            'ansible/ansible',
            'saltstack/salt',
            'fabric/fabric',
            'paramiko/paramiko',
            'boto/boto3',
            'aws/aws-cli',
            'docker/compose',
            'kubernetes/kubernetes',
            
            // Go (330-360)
            'golang/go',
            'kubernetes/kubernetes',
            'moby/moby',
            'gohugoio/hugo',
            'gin-gonic/gin',
            'beego/beego',
            'labstack/echo',
            'gorilla/mux',
            'go-chi/chi',
            'spf13/cobra',
            'spf13/viper',
            'urfave/cli',
            'sirupsen/logrus',
            'uber-go/zap',
            'stretchr/testify',
            'golang/mock',
            'grpc/grpc-go',
            'etcd-io/etcd',
            'prometheus/prometheus',
            'grafana/grafana',
            'traefik/traefik',
            'hashicorp/terraform',
            'hashicorp/vault',
            'hashicorp/consul',
            
            // Rust (360-380)
            'rust-lang/rust',
            'denoland/deno',
            'tauri-apps/tauri',
            'alacritty/alacritty',
            'sharkdp/bat',
            'sharkdp/fd',
            'BurntSushi/ripgrep',
            'starship/starship',
            'tokio-rs/tokio',
            'serde-rs/serde',
            'actix/actix-web',
            'rocket-rs/Rocket',
            'hyperium/hyper',
            'rust-lang/cargo',
            'rust-analyzer/rust-analyzer',
            
            // Ruby (380-400)
            'rails/rails',
            'jekyll/jekyll',
            'discourse/discourse',
            'fastlane/fastlane',
            'homebrew/brew',
            'sinatra/sinatra',
            'rspec/rspec',
            'rubocop/rubocop',
            'puma/puma',
            'sidekiq/sidekiq',
            
            // Java (400-430)
            'spring-projects/spring-boot',
            'spring-projects/spring-framework',
            'elastic/elasticsearch',
            'apache/kafka',
            'apache/spark',
            'apache/hadoop',
            'ReactiveX/RxJava',
            'square/retrofit',
            'square/okhttp',
            'google/guava',
            'junit-team/junit5',
            'mockito/mockito',
            'gradle/gradle',
            'apache/maven',
            
            // C/C++ (430-450)
            'torvalds/linux',
            'git/git',
            'redis/redis',
            'postgres/postgres',
            'mysql/mysql-server',
            'nginx/nginx',
            'curl/curl',
            'FFmpeg/FFmpeg',
            'opencv/opencv',
            'godotengine/godot',
            
            // Mobile (450-470)
            'flutter/flutter',
            'facebook/react-native',
            'ionic-team/ionic-framework',
            'expo/expo',
            'realm/realm-swift',
            'ReactiveX/RxSwift',
            'Alamofire/Alamofire',
            'square/picasso',
            'bumptech/glide',
            'airbnb/lottie-android',
            
            // DevOps/Tools (470-500)
            'docker/docker-ce',
            'kubernetes/kubernetes',
            'ansible/ansible',
            'terraform-providers/terraform-provider-aws',
            'helm/helm',
            'argoproj/argo-cd',
            'jenkins-x/jx',
            'gitlab-org/gitlab',
            'gitlabhq/gitlabhq',
            'gogs/gogs',
            'gitea/gitea',
            'drone/drone',
            'concourse/concourse',
            'spinnaker/spinnaker',
            'tektoncd/pipeline',
            'fluxcd/flux2',
            'rancher/rancher',
            'portainer/portainer',
            'netdata/netdata',
            'grafana/loki',
            'jaegertracing/jaeger',
            'open-telemetry/opentelemetry-collector',
            'elastic/kibana',
            'elastic/logstash',
            'getsentry/sentry',
            'minio/minio',
            'rclone/rclone',
            'restic/restic',
            'borgbackup/borg',
            'syncthing/syncthing',
        ]);
    }
}
